language: go
go:
  - 1.12.5
  
deploy:
- provider: script
  skip_cleanup: true
  script: docker run --rm --privileged -v $PWD:/go/code/yangon99/flowerss-bot -v /var/run/docker.sock:/var/run/docker.sock -w /go/code/yangon99/flowerss-bot -e GITHUB_TOKEN=$GITHUB_TOKEN goreleaser/goreleaser:latest-cgo release
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux